#!/bin/sh

. `dirname $0`/config.cnf

if [ $# -gt 0 ]; then
	phost=$1

	if [ $# -gt 1 ]; then
		step=$2
	else
		step=${def_step}
	fi

    if [ $# -gt 2 ]; then
		begin=$3
	else
		begin=$((${now}-${step}))
	fi

else
	echo "USAGE: gengraph <host> [step]"
	exit 1
fi

input=${input_dir}"/ping_"${phost}".log"

if [ ! -f ${input} ]; then
	exit 1
fi

echo "set title \"Smokeping on ${phost}\"" > /tmp/tmpgen
echo "set xlabel \"Time\"" >> /tmp/tmpgen 
echo "set ylabel \"ping (ms)\"" >> /tmp/tmpgen

echo "set grid" >> /tmp/tmpgen

echo "set xdata time" >> /tmp/tmpgen
echo "set timefmt \"%s\"" >> /tmp/tmpgen
echo "set format x \"%H:%m\"" >> /tmp/tmpgen
echo "set xrange [\"${begin}\":\"${end}\"]" >> /tmp/tmpgen

echo "set terminal png size 850,380" >> /tmp/tmpgen
echo "set output \"${output_dir}/${phost}.png\"" >> /tmp/tmpgen

echo "plot \"${input}\" using 1:2 with impulses linecolor rgbcolor \"green\" title ''" >> /tmp/tmpgen

gnuplot /tmp/tmpgen

rm /tmp/tmpgen
