#!/bin/sh

. `dirname $0`/config.cnf

if [ ! -d ${input_dir} ]; then
	echo "${input_dir} doesn't exists"
	exit 1
fi

for pinghost in ${hosts}; do
	pingtime=`ping -c 3 ${pinghost} | tail -n 1 | cut -d ' ' -f 4 | sed 's/\(.*\)\/\(.*\)\/\(.*\)\/\(.*\)/\2/'`

	echo ${now} ${pingtime} >> ${input_dir}/ping_${pinghost}.log
done
